### ISSUE TITLE
Can't bind to 'formgroup' since it isn't a known property of 'form'.

### ISSUE THREAD

**Issue by mamonaabdullah122** [start-angular/SB-Admin-BS4-Angular-8#343]
I want to create a Form.But when i write this code:
 [formgroup]="regForm">
 This error will be appear:
Can't bind to 'formgroup' since it isn't a known property of 'form'.
I also import this in my app.module.ts:
 import { FormsModule, ReactiveFormsModule } from '@angular/forms';
But nothing happend this error will e come.Someone help me to solve this issue.

**Comment by FatimaAbdullah122** [comment]
Same issue here.

**Comment by mamonaabdullah122** [comment]
Now What's the Solution.

**Comment by FatimaAbdullah122** [comment]
I Write this code it will work:
Import this in your sub folder:
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
[formGroup]="regForm">

**Comment by mamonaabdullah122** [comment]
Thanks Fatima Abdullah Its work.

**Comment by FatimaAbdullah122** [comment]
Well Come!
